version: "3.9"
services:
  db:
    image: postgres:14.0-alpine
    env_file: .env.example
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./public:/etc/caddy/public"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  app:
    image: llexx/app:cached
    build:
      context: .
      dockerfile: Dockerfile.production
    command: [ "/bin/sh", "-c", '/wait && npm test' ]
    # restart: on-failure
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432

volumes:
  pgdata:
