version: "3.9"
services:
  db:
    image: postgres:14.0-alpine
    env_file: .env.example
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    # command: [ "/bin/sh", "-c", '/wait && npm test' ]
    command: npm test
    depends_on:
      - db
    # environment:
    #   WAIT_HOSTS: db:5432

volumes:
  pgdata:
