FROM node:14.16

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

WORKDIR /app

COPY app/package.json .

COPY app/package-lock.json .

RUN npm install

COPY ./app .

COPY ./.env.example ./.env

EXPOSE 8080

CMD /wait && npm start
