FROM node:14.16-alpine

RUN apk add --no-cache --virtual build-deps python alpine-sdk autoconf libtool automake && \
  mkdir -p /prebuilds && cd /prebuilds && npm init -y && npm install sodium-native@3.1.1 && \
  apk del build-deps

ENV SODIUM_NATIVE_PREBUILD=/prebuilds/node_modules/sodium-native/

RUN apk add bash sqlite

WORKDIR /app

COPY app/package.json .
COPY app/package-lock.json .

RUN npm install

COPY app/. .

EXPOSE 8080

CMD npm test
