version: "3.9"
services:

  db:
    image: postgres:14.0-alpine
    # environment:
    #   POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: llexx/app:cached
    depends_on:
      - db

volumes:
  pgdata:
