version: "3.9"
services:

  db:
    image: postgres:14.0-alpine
    env_file: .env.example
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: llexx/app:cached
    restart: on-failure
    depends_on:
      - db

volumes:
  pgdata:
