version: "3.9"
services:
  app:
    build:
      context: .
    command: npm start
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./public:/etc/caddy/public"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    
volumes:
  node_modules:
  caddy_data:
  caddy_config:
