version: "3.9"
services:


  db:
    image: postgres:14.0-alpine
    env_file: app/.env.example
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: llexx/app:cached
    env_file: app/.env.example
    depends_on:
      - db

volumes:
  pgdata:
