compose:
	docker-compose up

compose-test:
	docker-compose -f docker-compose.yml up --abort-on-container-exit

# setup:
# 	npm ci
#
# start:
# 	npm start
#
# dev:
# 	npm run dev
#
# lint:
# 	npx eslint .
#
# test:
# 	npm test
#
# heroku-logs:
# 	heroku logs --tail
