name: run test and update image at Docker Hub
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: app/Dockerfile.production
          cache-from: type=registry,ref=app:cached
          cache-to: type=inline
          push: true
          tags: app:cached
      - 
        name: Check
        run:
          docker-compose --file docker-compose.yml up --abort-on-container-exit
